### ISSUE TITLE
Make a release to npm?

### ISSUE THREAD

**Issue by dblock** [ngyewch/smile-js#2]
I know this project is old, but was hoping to add smile support to https://github.com/opensearch-project/opensearch-api-specification similar to CBOR added in https://github.com/opensearch-project/opensearch-api-specification/pull/371.

**Comment by ngyewch** [comment]
Let me see what I can do.

**Comment by ngyewch** [comment]
Here you go https://www.npmjs.com/package/smile-js

**Comment by dblock** [comment]
I tried using it in https://github.com/opensearch-project/opensearch-api-specification/pull/386, getting this:

```
$ npm run test:spec--insecure -- --tests=tests/cat

> opensearch_api_tools@1.0.0 test:spec--insecure
> ts-node tools/src/tester/test.ts --opensearch-insecure --tests=tests/cat

Error: Cannot find module '/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/node_modules/smile-js/dist/smile-js.umd.cjs'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1016:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1009:15)
    at resolveExports (node:internal/modules/cjs/loader:529:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/tools/src/tester/ChapterReader.ts:18:1) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/node_modules/smile-js/package.json'
}
```

Not sure what I am doing wrong (yet) :)

**Comment by dblock** [comment]
I'll contribute a definition to https://github.com/DefinitelyTyped/DefinitelyTyped. Thanks for making a release!
