### ISSUE TITLE
Error importing in a TypeScript project (cannot find module dist/smile-js.umd.cjs)

### ISSUE THREAD

**Issue by dblock** [ngyewch/smile-js#3]
Coming from https://github.com/ngyewch/smile-js/issues/2#issuecomment-2215223825, importing into my TypeScript project fails with the following error at runtime.

```
$ npm run test:spec--insecure -- --tests=tests/cat

> opensearch_api_tools@1.0.0 test:spec--insecure
> ts-node tools/src/tester/test.ts --opensearch-insecure --tests=tests/cat

Error: Cannot find module '/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/node_modules/smile-js/dist/smile-js.umd.cjs'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1016:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1009:15)
    at resolveExports (node:internal/modules/cjs/loader:529:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/tools/src/tester/ChapterReader.ts:18:1) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/dblock/source/opensearch-project/opensearch-api-specification/dblock-opensearch-api-specification/node_modules/smile-js/package.json'
}
```

I fiddled with DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70007) but I think that's not the right way, since this project already exports its types.

**Comment by Xtansia** [comment]
Pretty sure this is because `package.json` specifies [here](https://github.com/ngyewch/smile-js/blob/master/package.json#L19) and [here](https://github.com/ngyewch/smile-js/blob/master/package.json#L24) that the CommonJS module file is `./dist/smile-js.umd.cjs` however that file doesn't exist, the only cjs file in `./dist/` is [`./dist/smile-js.cjs`](https://github.com/ngyewch/smile-js/blob/master/dist/smile-js.cjs).

**Comment by ngyewch** [comment]
> Pretty sure this is because `package.json` specifies [here](https://github.com/ngyewch/smile-js/blob/master/package.json#L19) and [here](https://github.com/ngyewch/smile-js/blob/master/package.json#L24) that the CommonJS module file is `./dist/smile-js.umd.cjs` however that file doesn't exist, the only cjs file in `./dist/` is [`./dist/smile-js.cjs`](https://github.com/ngyewch/smile-js/blob/master/dist/smile-js.cjs).

Ah, thanks! I'll fix that soon as I get the time.

**Comment by dblock** [comment]
I swear I searched through the code for the file before attempting something more complicated  ;)

Fix in https://github.com/ngyewch/smile-js/pull/6.
